import type { Metadata } from 'next';
import ThemeProvider from '@/theme';
// components
import { MotionLazy } from '@/components/animate/motion-lazy';

export const metadata: Metadata = {
  title: 'Ngmusic Apps',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <MotionLazy>{children}</MotionLazy>
        </ThemeProvider>
      </body>
    </html>
  );
}
